services:
  web:
    build: 
      context: 01_BackEnd/
      dockerfile: Dockerfile_Flask

    ports:
      - "8080:5001"

    depends_on:
      - redis
##    volumes:
##      - .:/code
  celery:
    build:
      context: 01_BackEnd/
      dockerfile: Dockerfile_Celery
    command: celery -A CeleryTask worker -l info --pool threads
#    command: ls -l

#    networks:
#      - redis-net
    depends_on:
      - redis

  redis:
    image: redis
#    container_name: redis
    ports:
      - "6379:6379"
#    networks:
#      - redis-net

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - /Volumes/PS2000/DB/Postgres_DB:/var/lib/postgresql/data
#networks:
#  redis-net:  
