FROM python:3.11.3-slim-bullseye
# Set the working directory in the container
WORKDIR /app

COPY . /app
RUN pip install -r requirements_flask.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
# Expose the port that the application will run on
EXPOSE 5001 

ENV HOME_AI_SERVICE='HOME_SERVICE_DOCKER'
# Start the application
CMD ["python", "FlaskApp.py"]