FROM python:3.11.3-slim-bullseye
# Set the working directory in the container
WORKDIR /app

COPY Service /app/Service
COPY CeleryTask /app/CeleryTask
COPY config.py requirements_celery.txt /app/
#RUN pip install celery[redis] \ 
#        & pip install lmstudio
RUN pip install -r requirements_celery.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
# Expose the port that the application will run on

ENV HOME_AI_SERVICE='HOME_SERVICE_DOCKER'